name: shapezio
base: core18 # the base snap is the execution environment for this snap
version: '1.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: shapez.io
description: |
  An open source base building game inspired by factorio.

grade: stable
confinement: strict

parts:
  shapezio:
    source: https://github.com/tobspr/shapez.io.git
    source-tag: "$SNAPCRAFT_PROJECT_VERSION"
    plugin: nodejs
    nodejs-version: "10.22.0"
    nodejs-package-manager: yarn
    build-packages:
      - ffmpeg
      - autoconf
      - automake
      - openjdk-11-jre-headless
      - wget
      - curl
      - unzip
    stage-packages:
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libnspr4
      - libnss3
    build-environment:
      - "PATH": "$SNAPCRAFT_PART_BUILD/node_modules/.bin:$SNAPCRAFT_PART_BUILD../npm/bin:$PATH"
    override-build: |
      snapcraftctl build
      yarn
      yarn add gulp
      yarn install
      cd electron
      yarn
      cd ../gulp
      yarn
      yarn gulp build.standalone-prod 
      yarn gulp standalone.prepare
      yarn gulp standalone.package.prod.linux64
      rm ../tmp_standalone_files/shapez.io-standalone-linux-x64/chrome-sandbox
      cp -a ../tmp_standalone_files/shapez.io-standalone-linux-x64/* $SNAPCRAFT_PART_INSTALL/

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false

apps:
  shapezio:
    extensions: [gnome-3-34]
    command: shapezio --no-sandbox
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - unity7
      - browser-sandbox
      - network
      - network-bind
      - gsettings
      - audio-playback
      - pulseaudio
      - opengl